### ISSUE TITLE
Sorting order of channels

### ISSUE THREAD

**Issue by themanfrommoon** [SirkoVZ/app-android#5]
Hi,

the app is very nice. Thanks a lot for that.

The only thing that is a little bit strange is the order the channels appears.
In the web frontend of the volkszähler, the channels are sorted by the alphabet, which makes a lot of sense for me.
But in the Volkszähler app, the channels seems to be unsorted.
See attached screenshots as reference.
Maybe it is possible to improve this?!
My suggestion and request is, that the channels should to be sorted in alphabetical order.

Thanks and best regards,
Chris
![vz frontend](https://cloud.githubusercontent.com/assets/28815063/26745820/b2774d5c-47ec-11e7-8328-1a3c8f0ad761.jpg)
![vzapp channels](https://cloud.githubusercontent.com/assets/28815063/26745822/b27ab2ee-47ec-11e7-8b74-b91d650c5196.jpg)
![vzapp einstellungen](https://cloud.githubusercontent.com/assets/28815063/26745819/b2751d02-47ec-11e7-825f-44992c10dcb4.jpg)
![vzapp hauptseite](https://cloud.githubusercontent.com/assets/28815063/26745821/b27a3274-47ec-11e7-9aa2-343d5c04fb2d.jpg)

**Comment by SirkoVZ** [comment]
I see, I will have a look at the next days.
Currently, I guess, the order is the same as created in the database...

**Comment by SirkoVZ** [comment]
Ich hab eine Sortierung eingebaut. Allerdings müssen einmalig (bzw. nach dem Ändern der entsprechenden Preference) die Kanäle neu eingelesen werden...
https://github.com/volkszaehler/app-android/releases/tag/v.0.9.3
